### ISSUE TITLE
Does the model only outputs HeatMaps?

### ISSUE THREAD

**Issue by oakkas** [mmittek/openpose-keras#1]
Hi mmittek,
Thanks for great job and sharing your work. I have couple of question.
Does the model only outputs heatmaps? Why it does not also provide PAFs?
Is there any way to find out connections so we can draw line? How can we identify and separate right and left hand. I also want to draw boxes that shows detecting hands and possibly tracking over time. 

One more thing; I tried model with hands wearing gloves and it wasn't able to find and key points. Do you have any idea what the issue would be?

Any suggestions and ideas will be appreciated.

Best,

Oguz

**Comment by mmittek** [comment]
Thank you for looking into my work! I really appreciate it! I am in the process of addressing your questions and I will publish them in the readme. Please subscribe to this repo to get notified when this issue is closed.
Thank you!
